### ISSUE TITLE
Is this plugin still maintained

### ISSUE THREAD

**Issue by dkastl** [flowdock/redmine_flowdock#11]
I'm wondering if this plugin is still maintained and supported as it has not received any update for quite some time. It mentions a pretty old version in the Readme and according to the Flowdock documentation the API token authentication is deprecated:

```
API tokens

Deprecated. OAuth is the preferred way of authenticating with Flowdock and using our APIs. See the documentation and add your own developer application.
```

Is this plugin safe to use?

**Comment by coldpour** [comment]
Hey @dkastl, unfortunately our priorities have shifted away from Redmine and so we are not maintaining this code anymore. You are welcome to fork this and make it work for you.

**Comment by dkastl** [comment]
Same here. We're not using Flowdock anymore.
